### ISSUE TITLE
Funky Split Second Image Showing

### ISSUE THREAD

**Issue by benjaminrobinson** [DC-OSSE/LearnDC_v2#106]
This image shows for what seems like a split second when reloading a page or moving from one school page to another (by changing the numbers in the URL)...not sure why its happening but I figured I'd bring it up...

![image](https://cloud.githubusercontent.com/assets/7928978/6082919/d121eb18-adf2-11e4-8b89-a04927e38524.png)

**Comment by benjaminrobinson** [comment]
Just to let everyone know, the page doesn't display this image for very long...I had to get a screenshot at exactly the right moment!

**Comment by cmgiven** [comment]
Yes, I've seen this too. Not just on School Profiles pages. Just started today, though, so possible related to the Acquia transition somehow?

**Comment by benjaminrobinson** [comment]
Glad I'm not the only one...was starting to think I was getting OSSE related paranoia, which would be very strange!

**Comment by cmgiven** [comment]
Oh, right, I forgot we added that subliminal messaging feature.

**Comment by benjaminrobinson** [comment]
:dizzy_face:

**Comment by mepps** [comment]
I've been able to figure out which svg is, I will ask a designer if they can resize it.

**Comment by benjaminrobinson** [comment]
So do we now why this is happening?  Is it related to Acquia?

**Comment by mepps** [comment]
We resized the image and it has been fixed on staging and prod. Can't show a screen shot since it's not happening :).

**Comment by benjaminrobinson** [comment]
Subliminal messaging, I will miss thee!...:)

**Comment by benjaminrobinson** [comment]
I am still seeing it...

**Comment by mepps** [comment]
Try clearing your browser caches. It's not showing up for me anywhere I've cleared the caches.

**Comment by gwenrr** [comment]
Just cleared my browser cache and it is still happening for me

**Comment by benjaminrobinson** [comment]
Same here...

**Comment by mepps** [comment]
Made new changes. Can you guys clear caches again and see if it's happening?

**Comment by benjaminrobinson** [comment]
I don't see it anymore!

**Comment by mepps** [comment]
Yay!

**Comment by benjaminrobinson** [comment]
Still seeing it occasionally for whatever reason...

**Comment by gwenrr** [comment]
Can we have an update on where this is? Thanks!

**Comment by gwenrr** [comment]
In other words, it's still happening. (Just got an email from someone asking about it.)

**Comment by cmgiven** [comment]
@gwenrr, we'd be happy to schedule a call to discuss what is needed here and how that work should flow. Let @wardkatherine and me know what work's best for you.

**Comment by benjaminrobinson** [comment]
Welcome to GitHub, Katherine!  Should I add her to the Collaborator list, @cmgiven?

**Comment by cmgiven** [comment]
Sure! Didn't realize she wasn't on (she's on the Social Driver repos). Thanks, Ben.

**Comment by cmgiven** [comment]
Maggie has just deployed a new fix to production. I believe I have confirmed that this resolves the issue. Please let us know if you spot a recurrence.
